name: Lighthouse
on: push
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run Lighthouse on urls and upload data to private lhci server
        uses: treosh/lighthouse-ci-action@v8
        with:
          urls: |
            https://www.magentaa11y.com/checklist-web/alert/
            https://www.magentaa11y.com/checklist-web/animation/
            https://www.magentaa11y.com/checklist-web/button/
            https://www.magentaa11y.com/checklist-web/carousel/
            https://www.magentaa11y.com/checklist-web/checkbox/
            https://www.magentaa11y.com/checklist-web/date-picker/
            https://www.magentaa11y.com/checklist-web/expander/
            https://www.magentaa11y.com/checklist-web/figure/
            https://www.magentaa11y.com/checklist-web/footer/
            https://www.magentaa11y.com/checklist-web/form/
            https://www.magentaa11y.com/checklist-web/header/
            https://www.magentaa11y.com/checklist-web/heading/
            https://www.magentaa11y.com/checklist-web/hint-help-error/
            https://www.magentaa11y.com/checklist-web/html/
            https://www.magentaa11y.com/checklist-web/iframe/
            https://www.magentaa11y.com/checklist-web/image/
            https://www.magentaa11y.com/checklist-web/link/
            https://www.magentaa11y.com/checklist-web/listbox-autocomplete/
            https://www.magentaa11y.com/checklist-web/main/
            https://www.magentaa11y.com/checklist-web/modal-dialog/
            https://www.magentaa11y.com/checklist-web/nav/
            https://www.magentaa11y.com/checklist-web/number-input/
            https://www.magentaa11y.com/checklist-web/pagination/
            https://www.magentaa11y.com/checklist-web/password-input/
            https://www.magentaa11y.com/checklist-web/progress-bar/
            https://www.magentaa11y.com/checklist-web/radio/
            https://www.magentaa11y.com/checklist-web/range-slider/
            https://www.magentaa11y.com/checklist-web/scrolling-container/
            https://www.magentaa11y.com/checklist-web/search/
            https://www.magentaa11y.com/checklist-web/select/
            https://www.magentaa11y.com/checklist-web/separator/
            https://www.magentaa11y.com/checklist-web/single-page-application/
            https://www.magentaa11y.com/checklist-web/skip-link/
            https://www.magentaa11y.com/checklist-web/snackbar-toast/
            https://www.magentaa11y.com/checklist-web/star-rating/
            https://www.magentaa11y.com/checklist-web/stepper-input/
            https://www.magentaa11y.com/checklist-web/sticky-content/
            https://www.magentaa11y.com/checklist-web/strikethrough/
            https://www.magentaa11y.com/checklist-web/tab-panel/
            https://www.magentaa11y.com/checklist-web/table/
            https://www.magentaa11y.com/checklist-web/text-input/
            https://www.magentaa11y.com/checklist-web/toggle-switch/
            https://www.magentaa11y.com/checklist-web/tooltip/
            https://www.magentaa11y.com/checklist-web/video-audio/
          serverBaseUrl: ${{ secrets.LHCI_SERVER_URL }}
          serverToken: ${{ secrets.LHCI_SERVER_TOKEN }}